### ISSUE TITLE
Unnecessary nav links

### ISSUE THREAD

**Issue by redjonzaci** [superfly/docs#1021]
Should the last links in the nav of https://fly.io/docs/postgres/ be there?
If we want to return to the main nav, maybe there should be a "Back" link at the top of the nav.

<img width="415" alt="image" src="https://github.com/superfly/docs/assets/73707194/9a8c0340-cf42-4a5d-80f9-ded7fed1a8d3">

**Comment by andie787** [comment]
closing: we have a Docs Home link now and the other links are just part of a layout that will be updated at some point.
