### ISSUE TITLE
Is Pricing section right in "Redis by Upstash" page?

### ISSUE THREAD

**Issue by redjonzaci** [superfly/docs#1022]
Are these our prices?
If so, are the table column names correct?
Should we maybe add this to https://fly.io/docs/about/pricing/?

<img width="518" alt="image" src="https://github.com/superfly/docs/assets/73707194/5100c72f-33ad-46bb-8a5b-b575ed7bb708">

**Comment by andie787** [comment]
closing: this table no longer exists after a pricing update.
