### ISSUE TITLE
Paragraph might confuse users

### ISSUE THREAD

**Issue by redjonzaci** [superfly/docs#1036]
It confused me at least. Should we maybe:
- explain why we have this or
- move it to a `details` section with the `summary` being the reason why this is included or
- move it to a Troubleshooting page and link to it?

<img width="555" alt="image" src="https://github.com/superfly/docs/assets/73707194/0e86f44c-9a3b-4df6-984f-7725105dfab1">

**Comment by rubys** [comment]
flyctl is written in go.  There are go libraries that you can import like https://github.com/skratchdot/open-golang which will "open" an application or a browser.  If you look at the [description](https://github.com/skratchdot/open-golang#description) for that library, you can see that it runs a different command based on the operating system.

This library detects WSL as linux (which is it) and tries to run xdg-open, which is not included in WSL.  WSL includes wslview which will open a browser window and by creating xdg-open as a symbolic link to wslview you can get flyctl to open a browser window on WSL.

**Comment by redjonzaci** [comment]
Okay, I understand now and I feel like it would be helpful to have this info in the docs.
What do you think @andie787?

**Comment by rubys** [comment]
This information current exists on two pages:
  * https://fly.io/docs/hands-on/sign-in/
  * https://fly.io/docs/getting-started/log-in-to-fly/

My sense is that people who land on those pages are looking to solve a problem, and are not looking for a deep explanation.

**Comment by redjonzaci** [comment]
But it doesn't explain what you explained to me or at least say: "if you have this error message, do this...".

Why is that important? Because I am left there wondering if I need to run the command or not.

I mean it's not that important, but just sharing my perspective.
