### ISSUE TITLE
Unable to get Laravel app running

### ISSUE THREAD

**Issue by redjonzaci** [superfly/docs#1037]
While following https://fly.io/docs/laravel/:
- There's no link to PHP download page
- When I try to run `php artisan serve` the first time, I get an error about `vendor/autoload.php`
I tried `composer install` and `composer dump-autoload` to get past that error, but then encountered this:

<img width="661" alt="image" src="https://github.com/superfly/docs/assets/73707194/7a89b76f-41b8-4361-914a-2a4d7ee8f7d1">

I am using Windows.

**Comment by redjonzaci** [comment]
I made it work by adding `--ignore-platform-req=ext-fileinfo` to `composer create-project laravel/laravel fly-laravel`.
Opening a PR soon to update the docs...

**Comment by redjonzaci** [comment]
I am not satisfied about where I added the note or how it may look, but feedback welcome!

**Comment by andie787** [comment]
Closed per related PR
