### ISSUE TITLE
Not every app can point to "fly-hello-laravel.fly.dev"

### ISSUE THREAD

**Issue by redjonzaci** [superfly/docs#1039]
https://fly.io/docs/laravel/

I think this can be removed. If a user tries this and another user has already used that URL, then I guess it would give them an error?

<img width="505" alt="image" src="https://github.com/superfly/docs/assets/73707194/df96f096-f38a-487c-abc6-0966f91d574d">

**Comment by andie787** [comment]
Directly below that example, it says:

> Replace this with the URL your app will be served on (by default, "https://<your-app-name>.fly.dev").

So I think it's okay.
