### ISSUE TITLE
Broken link on volumes documentation page

### ISSUE THREAD

**Issue by lpil** [superfly/docs#1067]
Hello!

The anchor that reads "How to scale an app with volumes attached" on [this page](https://fly.io/docs/reference/volumes/) has an empty `href`, it doesn't go anywhere.

https://github.com/superfly/docs/blob/04ee4638e894c6045bbb0ca04fb14584f4ab2b24/reference/volumes.html.markerb#L47

Thanks,
Louis

**Comment by Lucais11** [comment]
Thanks for bringing this to our attention, I'm on it!
