### ISSUE TITLE
Outdated `litefs` usage instructions on config

### ISSUE THREAD

**Issue by tylerritchie** [superfly/docs#1155]
I'm _pretty_ confident this [section of the `litefs` config docs](https://github.com/superfly/docs/blob/19de0df07900e319f5a4ac80e4c5bd4e24ef9d1a/litefs/config.html.markerb#L24-L26) are out of date

old and busted:
```sh
litefs -config /path/to/litefs.yml
```

new hotness:
```sh
litefs mount -config /path/to/litefs.yml

litefs run -config /path/to/litefs.yml
```

https://github.com/superfly/docs/blob/main/litefs/config.html.markerb#L25

@benbjohnson: FYI

if that seems right i can open a PR.

**Comment by tylerritchie** [comment]
i feel emboldened, this would match what i've seen, but i don't know Go

https://github.com/superfly/litefs/blob/e7690439d2a06d3240dd7bd5da0596f3d270e89c/cmd/litefs/main.go#L36-L79

- `[.run()` receives `args > 0`](https://github.com/superfly/litefs/blob/main/cmd/litefs/main.go#L39-L41) and `args[1:]` is the string config`"-config"`
- regardless, it doesn't matter, we end in the [`default` case](https://github.com/superfly/litefs/blob/main/cmd/litefs/main.go#L73) and print usage information

**Comment by benbjohnson** [comment]
Good catch! I made a PR for the change and merged it in. It should be live in a few minutes. Thanks! https://github.com/superfly/docs/pull/1172
