### ISSUE TITLE
New Doc Illustrations

### ISSUE THREAD

**Issue by ahruygt** [superfly/docs#1259]
All of these images are ready to be added to the docs.  I added a link to each page. If you need me to adjust them please let me know.  Thanks so much!!

**Comment by ahruygt** [comment]
Illustration for docs: https://fly.io/docs/getting-started/troubleshooting/
and https://fly.io/docs/apps/trouble-host-unavailable/

![Image](https://github.com/superfly/docs/assets/7118680/709f62ec-4c40-4f78-8922-0f65f68845b1)

**Comment by ahruygt** [comment]
Connect to App: https://fly.io/docs/getting-started/app-services/

![Image](https://github.com/superfly/docs/assets/7118680/e7e3884c-1120-4afc-912e-cb78e921cb33)

**Comment by ahruygt** [comment]
Launch a New Fly App: https://fly.io/docs/apps/launch/

![Image](https://github.com/superfly/docs/assets/7118680/82c37a91-051a-49b9-abae-e12254f9ca8b)

**Comment by andie787** [comment]
wow! love these!

**Comment by ahruygt** [comment]
Image for this doc: https://fly.io/docs/apps/deploy/
![Image](https://github.com/superfly/docs/assets/7118680/82a0fb55-81e2-417a-8fef-b3beaa644122)

**Comment by ahruygt** [comment]
For doc: https://fly.io/docs/apps/info/

![Image](https://github.com/superfly/docs/assets/7118680/76d09133-c9dc-4b27-a7d2-b543ca98f373)

**Comment by ahruygt** [comment]
Scale Number of Machines Doc: https://fly.io/docs/apps/scale-count/


![Image](https://github.com/superfly/docs/assets/7118680/d0cfab33-153b-4edf-b309-b94c69680daa)

**Comment by ahruygt** [comment]
For Auto Start and Stop: https://fly.io/docs/apps/autostart-stop/

![Image](https://github.com/superfly/docs/assets/7118680/ff6e8f88-b58d-46f9-adc9-86b93674f4a3)

**Comment by ahruygt** [comment]
Get Custom Domain: https://fly.io/docs/networking/custom-domain/

![Image](https://github.com/superfly/docs/assets/7118680/818aa9dd-812f-4f77-b449-a21e4a880d3c)

**Comment by ahruygt** [comment]
Restart and App: https://fly.io/docs/apps/restart/


![Image](https://github.com/superfly/docs/assets/7118680/8671902e-dce4-45ac-8309-7245b54def43)

**Comment by hkfoster** [comment]
Done and done!
