### ISSUE TITLE
Postgres instructions for `fly image update` should say how to notice a major version update

### ISSUE THREAD

**Issue by jyasskin** [superfly/docs#1269]
https://fly.io/docs/postgres/managing/upgrades/ says that "_The update won’t go ahead if the major Postgres version in your existing Postgres app does not match that in the newest postgres-ha release._", but in practice the output for such a failed upgrade ("No changes to apply" for an attempted upgrade from `flyio/postgres:14.6 (v0.0.41)`) appears to be the same as for an image that actually is on the latest version.

This does seem to be the [latest version of that package on Docker](https://hub.docker.com/r/flyio/postgres/tags), and the release linked from "[latest release](https://github.com/fly-apps/postgres-ha/releases)" on https://fly.io/docs/postgres/managing/upgrades/ is actually the older 0.0.39, but according to https://community.fly.io/t/improved-postgres-clustering-with-repmgr-preview/10668 and https://community.fly.io/t/point-in-time-recovery-for-postgres-flex-using-barman/13185, you seem to have published new versions under https://hub.docker.com/r/flyio/postgres-flex/tags that are up to 0.0.46.

How can users systematically notice that it's time to upgrade?

**Comment by andie787** [comment]
Making some doc changes to the Postgres Upgrade page for this. The reason you couldn't upgrade isn't because of major versions, but because postgres-ha and postgres-flex are totally different images. I wrote a note about that. Let me know if it doesn't make sense or would not have helped in your scenario!
