### ISSUE TITLE
Document the machines API and CLI commands

### ISSUE THREAD

**Issue by jsierles** [superfly/docs#132]
We need a solid docs page for the upcoming launch of Machines.

Reference docs:
https://flyio.slab.com/posts/how-to-build-user-functions-with-fly-machines-1069s2nf
https://flyio.slab.com/posts/fly-machines-li5891n6
https://flyio.slab.com/topics/docs-7dw6muiw

**Comment by andie787** [comment]
stale issue - this is all done!
