### ISSUE TITLE
fly launch --no-deploy vs --no deploy typo

### ISSUE THREAD

**Issue by vielmetti** [superfly/docs#1321]
There's a "Deployment" section of https://fly.io/docs/reference/fly-launch/ where it discusses 

```
The fly launch command might deploy your new app for the first time if you accept the defaults or after you tweak the app’s settings. You can stop fly launch from deploying the new app right away with fly launch --no deploy.
```

If you do this you get the error message 

`Error: unknown flag: --no`

The fix is simple, replace `--no deploy` with `--no-deploy` in the docs at https://github.com/superfly/docs/blob/8af15f73f850153a799dcb32aaab0ace2d0951fb/reference/fly-launch.html.md?plain=1#L60

This looks like the only version of this typo in the docs, based on

https://github.com/search?q=repo%3Asuperfly%2Fdocs%20%22--no%20deploy%22&type=code

**Comment by andie787** [comment]
fixed by #1323
