### ISSUE TITLE
404 in documentation search results

### ISSUE THREAD

**Issue by typesanitizer** [superfly/docs#137]
Looks like there is a bug in the caching of search results or the redirect setup. See attached screen recording. One of the search results for 'latency' leads to a 404.

https://user-images.githubusercontent.com/7187503/167277072-733b2e3a-7178-47ef-97a7-3b5cfc60bec0.mov

(Apologies if this is the wrong GitHub repo to report this issue.)

**Comment by catflydotio** [comment]
Probably fixed by @jeregrine https://github.com/superfly/landing/pull/379
