### ISSUE TITLE
Private Networking - implies tunnel is up without running wg-quick

### ISSUE THREAD

**Issue by colemickens** [superfly/docs#1383]
Look at the "Dealing with Defaults" section. It shows the tunnel working before the docs have the user run `wg-quick`.

Looks like maybe a mistake from moving the wg-quick instructions to being OS-specific and not (re)moving the the part where you query DNS to show it working after `wg-quick up`.

![Uploading screenshot-1709062220.png…]()

**Comment by colemickens** [comment]
Brilliant work there GitHub. 
![screenshot-1709062220](https://github.com/superfly/docs/assets/327028/4debf7fd-c957-43af-820b-448448023938)

**Comment by andie787** [comment]
Oh good point! Looks like this doc has been structured this way forever. It could probably use a review/update, so we'll take a look.

**Comment by andie787** [comment]
I updated most of the doc, numbered the main steps in Private Network VPN and turned that section into a note and got rid of the "dealing with defaults" title altogether. Moved the dig examples into the Test the VPN tunnel section.
