### ISSUE TITLE
Prometheus `curl` query requires (!?) `query=`

### ISSUE THREAD

**Issue by DazWilkin** [superfly/docs#144]
https://fly.io/docs/reference/metrics/#manually

As documented yields:

```console
{
  "status": "error",
  "errorType": "422",
  "error": "missing `query` arg"
}
```

But prefixing the PromQL with `query=` appears to fix it:

`query=sum(rate(fly_edge_http_responses_count{app="$APP"}[5m])) by (status)`

**Comment by wjordan** [comment]
Fixed by #171. Thanks for reporting this issue!
