### ISSUE TITLE
LiteFS docs don't work properly on Firefox 124.0b9 (64-bit)

### ISSUE THREAD

**Issue by stv8** [superfly/docs#1456]
**Link to the affected page or pages**

https://fly.io/docs/litefs/

**Describe what part of the site needs improvement**

When using Firefox, clicking the headers on the sidebar doesn't open them up. This appears to only happen on the LiteFS section of the docs as the rest of the site works.

I'm on Firefox Firefox 124.0b9 (64-bit)

**Additional info**

https://github.com/superfly/docs/assets/5158539/d76a399f-6525-43b4-9298-3297c61fa72c

**Comment by hkfoster** [comment]
Should be good to go 👍
