### ISSUE TITLE
Python docs is incorrect. 

### ISSUE THREAD

**Issue by Carreau** [superfly/docs#147]
It mixes deploying with buildpacks and docker. 

Flyctl launch will create a docker file in CWD which 

1) is wrong and try to run demo.wgi, and call manage.py that does not exists. 
2) the docs mention buildpack so I guess fly.toml needs a 

```
[build]
  builder = "paketobuildpacks/builder"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]
```

**Comment by andie787** [comment]
stale issue - Python docs and scanners have been updated
