### ISSUE TITLE
Improve Documentation on Moving Applications Between Organizations Using fly apps move Command

### ISSUE THREAD

**Issue by Lucais11** [superfly/docs#1524]
**Link to the affected page or pages**

- https://fly.io/docs/flyctl/apps-move/#main-content-start

**Describe what parts of the doc need improvement**

The current documentation covers the basic usage of the `fly apps move` command but lacks detailed explanations about what is transferred along with the application and what remains behind. Here are specific areas that come to mind that need improvement:

1. Environment Variables and Secrets:

Confirm that these are transferred over as they are generally embedded within the `fly.toml` file for the specific application.

2. Certificates and Domain Names:

Clarify that these remain bound to the specific application.

3. External Services Dependencies:

- Redis: Clarify that services like Fly Upstash Redis require a new setup and do not move with the application.
- Postgres: Provide guidance on the necessary steps for migrating Postgres applications, suggesting the use of the `fly postgres import` command.
- LiteFS, Tigris, Supabase: Explain how these external dependencies are managed during the move, including any necessary steps to ensure their functionality post-move.

4. Operational Impact:

Highlight the requirement for a complete shutdown and restart of the application during the move, leading to potential downtime.

**Additional info**

- Gather insights from those who have assisted users or have firsthand experience with the `fly apps move` process to identify common challenges and areas where users tend to get stuck.
- Include specific examples, warnings, or tips. We should consider creating a dedicated page or article in the documentation that focuses solely on transferring apps to another organization.
- Identify any areas in the current process that could be streamlined or clarified to make transitions smoother.

**Comment by andie787** [comment]
hey @Lucais11

I agree that the flyctl help docs could use some more info! And that a new page in the main docs about moving an app is a great idea. The help could link to it.

For the flyctl help, we should keep it short and include the main issues with moving an app this way. Then in the larger doc you'll have room to go into the details.

We can do these in PRs or you can start a slab doc and we can work from there.

**Comment by andie787** [comment]
fixed by #1682
