### ISSUE TITLE
Issue with the "Nginx at the edge" doc

### ISSUE THREAD

**Issue by Yiming-Liao** [superfly/docs#1531]
I found an issue with this document.

Title: Nginx at the edge
Location: /docs/app-guides/nginx-at-the-edge/
Source: https://github.com/superfly/docs/blob/main/app-guides/nginx-at-the-edge.html.markerb

### Describe the issue

./nginx.conf
Nginx needs a configuration file, here’s a basic configuration for proxying requests to a _Heroku_ application. Save this to your working directory as nginx.conf:

Heroku => Fly.io ? 😂

**Comment by andie787** [comment]
Actually, this doc was about running the nginx proxy on Fly.io and connecting it to, for example, a Heroku app. That said, since this document is long obsolete and not being update, we're just going to remove it.
