### ISSUE TITLE
Request the use of your brandmark

### ISSUE THREAD

**Issue by LitoMore** [superfly/docs#1540]
Title: Request the use of your brandmark
Location: /docs/about/brand/
Source: https://github.com/superfly/docs/blob/main/about/brand.html.markerb

### Describe the issue

I'm the maintainer of the [Simple Icons](https://github.com/simple-icons/simple-icons) project. 
We are currently [migrating our CDN service from Vercel to Fly.io](https://github.com/LitoMore/simple-icons-cdn/issues/10). We want to put a shields.io icon in the readme of my project to inform users that my project is Powered by Fly.io. But we need your approval on the icon. Like these below:

![][flyio-badge]
![][flyio-badge-balloon]
![][flyio-badge-balloon2]

The problem is that Simple Icons does not support multiple colors for the icons. All of them are defined with the actual monochrome. Here is the pull request for the Fly.io icon:

- https://github.com/simple-icons/simple-icons/pull/11025

Do you have any suggestions?

[flyio-badge]: https://img.shields.io/badge/Powered_by_Fly.io-2A1863.svg?style=flat-square&logo=data:image/svg%2bxml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+Rmx5LmlvPC90aXRsZT48cGF0aCBmaWxsPSIjZmZmZmZmIiBkPSJNMTYuNzgyIDMuNjdoMi43NjRBNC40NTYgNC40NTYgMCAwIDEgMjQgOC4xMjJ2OS43MTdhNC40NTYgNC40NTYgMCAwIDEtNC40NTQgNC40NTRoLS4yMThjLTEuMjY1LS4xOTgtMS44MTQtLjU3Ny0yLjIzNy0uODk4bC0zLjUxNC0yLjg5YS40OTYuNDk2IDAgMCAwLS42MjIgMGwtMS4xNDIuOTRMOC42IDE2LjgwMmEuNDk0LjQ5NCAwIDAgMC0uNjIyIDBsLTQuNDY2IDMuOTNjLS45LjczLTEuNDk0LjU5NS0xLjg4LjU1M0E0LjQ1IDQuNDUgMCAwIDEgMCAxNy44NFY4LjEyM2E0LjQ1NiA0LjQ1NiAwIDAgMSA0LjQ1NC00LjQ1NGgyLjc1N2wtLjAwNS4wMTEtLjA5My4yNzEtLjAyOS4wOTMtLjEyNS41NTUtLjAxNy4wOTgtLjA1NS41NTYtLjAwNy4xNTItLjAwMS4wNTQuMDA1LjI1NS4wMTIuMTQ5LjAzMS4yMzQuMDQuMjEuMDQ3LjE5NC4wNi4yMS4xNTguNDQ0LjA1Mi4xMzQuMjc1LjU4LjA5Ny4xNzkuMzE4LjU0NS4xMjEuMTk3LjQ0NC42NTMuMDY0LjA4Ni41NzcuNzUxLjE4Ni4yMzEuNjYuNzcuMTM1LjE0OS41NDMuNTg0LjIxNS4yMjMuMzU1LjM1My0uMDcuMDYtLjA0NS4wNGE0IDQgMCAwIDAtLjM0My4zNThxLS4wNzcuMDktLjE0Ny4xODgtLjEwNy4xNDgtLjE5LjMxLS4wNDMuMDg1LS4wNzcuMTc0YTEuNiAxLjYgMCAwIDAtLjEwMy40NjlsLS4wMDIuMTM5Yy4wMDUuMTk2LjA0NS4zODkuMTE4LjU3YTEuNiAxLjYgMCAwIDAgLjMxNy40OTggMS42IDEuNiAwIDAgMCAuMzM1LjI3M3EuMTU4LjA5Ny4zMzMuMTU3Yy4yNTMuMDg2LjUyMS4xMTcuNzg3LjA5aC4wMDFhMS44IDEuOCAwIDAgMCAuNjUtLjE5MyAyIDIgMCAwIDAgLjI0Ny0uMTYgMS42IDEuNiAwIDAgMCAuNS0uNjY1Yy4wODItLjIwNC4xMjItLjQyMy4xMTgtLjY0MmwtLjAwNi0uMTE1YTEuNiAxLjYgMCAwIDAtLjEwNy0uNDQzcS0uMDM3LS4wOTItLjA4NC0uMTgtLjA4Ni0uMTYzLS4xOTYtLjMxLS4wNS0uMDY4LS4xMDMtLjEzM2E0IDQgMCAwIDAtLjM4Mi0uNGwtLjA5Ny0uMDgyLjE2My0uMTYuNy0uNzMyLjI0Mi0uMjY1LjM3Ni0uNDI0LjI0NS0uMjg2LjM0OS0uNDI1LjIzNi0uMjk3LjM0Ny0uNDY0LjE3NS0uMjQuMjQ5LS4zNzEuMjA3LS4zMTcuMzktLjY3OS4yMjMtLjQ0NS4wMDYtLjAxNC4xNy0uNDEzcS4wMDQtLjAwOC4wMDYtLjAxN2wuMTg0LS41NzMuMDItLjA4NC4wOC0uNDU2LjAxNS0uMTI0LjAwNS0uMDc2LjAwNS0uMjg2LS4wMDEtLjA1My0uMDE1LS4yNTYtLjAxOC0uMTk5LS4wOS0uNTczLS4wMDYtLjAyMy0uMTE2LS40MjQtLjA0LS4xMTd6bTEuMzE0IDEyLjExN2ExLjA3NSAxLjA3NSAwIDAgMC0xLjA1NSAxLjA1NWMuMDA4LjU3Ni40OCAxLjA0NyAxLjA1NSAxLjA1NWExLjA3NiAxLjA3NiAwIDAgMCAxLjA1Ni0xLjA1NSAxLjA3NiAxLjA3NiAwIDAgMC0xLjA1Ni0xLjA1NW0tMi4wNzcgNi41MDdoLTUuNDI3Yy0uMjc4IDAtLjMxNy0uMjY0LS4xMzgtLjQxMyAyLjY0OS0yLjIyIDIuNjQyLTIuMjI3IDIuNjQyLTIuMjI3YS4yOS4yOSAwIDAgMSAuMzc1IDBzMi40ODkgMi4wNjIgMi42ODYgMi4yMjdjLjE3OS4xNS4xNC40MTMtLjEzOC40MTNtLTQuMDA0LTguODUuMDI4LjAwOHEuMDE0LjAwNi4wMjUuMDE2bC4wMjMuMDJxLjA4Ny4wODEuMTY4LjE2Ny4wNTguMDYxLjExMS4xMjYuMDY4LjA4Mi4xMjcuMTcxLjAyNS4wNC4wNDYuMDgxLjAyLjAzNi4wMzQuMDc0LjAyOC4wNjYuMDM1LjEzN3YuMDg4YS41LjUgMCAwIDEtLjI0LjM5My43LjcgMCAwIDEtLjI5LjA5NmwtLjExLjAwMy0uMDkxLS4wMDhhMSAxIDAgMCAxLS4xMjctLjAzMS42LjYgMCAwIDEtLjEyLS4wNTZsLS4wNzItLjA1M2EuNS41IDAgMCAxLS4xNjMtLjI4bC0uMDA5LS4wNTYtLjAwMi0uMDg0cS4wMDItLjAzNC4wMS0uMDY4YS43LjcgMCAwIDEgLjA1My0uMTQycS4wNDQtLjA4NS4xLS4xNjMuMDk0LS4xMjcuMjAyLS4yNC4wNy0uMDc0LjE0NC0uMTQzbC4wMzYtLjAzMmMuMDI0LS4wMTYuMDI1LS4wMTYuMDUzLS4wMjR6bS0uMTgtMTEuNzM3LjAxLS4wMDF2OS44NDJsLS4wMjQtLjA0NmEyOCAyOCAwIDAgMS0uOTA0LTEuODMyIDIwIDIwIDAgMCAxLS42MTQtMS41MzYgMTIgMTIgMCAwIDEtLjM3LTEuMjY1IDcgNyAwIDAgMS0uMTYxLTEuMDMzIDUgNSAwIDAgMS0uMDA5LS40NDdxLjAwNC0uMTk0LjAxNi0uMzg5LjAyLS4zMDYuMDYzLS42MDguMDM1LS4yMzkuMDktLjQ3My4wNDMtLjE4Ny4xLS4zNy4wODItLjI2Mi4xOTctLjUxMy4wNDItLjA5LjA5LS4xOGMuMTktLjM1MS40NDctLjY3NS43ODUtLjg5MmExLjY0IDEuNjQgMCAwIDEgLjczLS4yNTdtMS4yNzYuMDI1LjY2Mi4xODhhNCA0IDAgMCAxIC44NzQuNDQ1IDMuNSAzLjUgMCAwIDEgLjkzOC45MzcgMy41IDMuNSAwIDAgMSAuMzY0LjcgNC4xIDQuMSAwIDAgMSAuMjUzIDEuMTM2cS4wMTMuMTUzLjAxNi4zMDYuMDA0LjE0Mi0uMDA2LjI4NGEzLjIgMy4yIDAgMCAxLS4xMTkuNjI2IDUgNSAwIDAgMS0uMTcxLjQ5MiA3IDcgMCAwIDEtLjI3My41ODhjLS4yMi40MjYtLjQ3NS44MzQtLjc0NiAxLjIyOGExOSAxOSAwIDAgMS0xLjA3NyAxLjQwNSAyNyAyNyAwIDAgMS0xLjI5MSAxLjQzMiAyNyAyNyAwIDAgMCAuODUtMS43NCAyMiAyMiAwIDAgMCAuNDEzLS45OTUgMTYgMTYgMCAwIDAgLjM4NS0xLjEyIDExIDExIDAgMCAwIC4yMjEtLjg1OXEuMDgxLS4zNzMuMTItLjc1MS4wMzMtLjMxNi4wMjUtLjYzM2E5IDkgMCAwIDAtLjAxNS0uMzg4IDYuNiA2LjYgMCAwIDAtLjI2LTEuNTM0IDUgNSAwIDAgMC0uMjEtLjU1M2MtLjE5My0uNDIyLS40NjQtLjgxNy0uODMtMS4xMDVaIi8+PC9zdmc+

[flyio-badge-balloon]: https://img.shields.io/badge/Powered_by_Fly.io-2A1863.svg?style=flat-square&logo=data:image/svg%2bxml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+Rmx5LmlvPC90aXRsZT48cGF0aCBmaWxsPSIjZmZmZmZmIiBkPSJtMTEuOTkzIDAtLjIxNC4wMDMtLjU0Ny4wMjgtLjI3Ni4wMjUtLjQwNC4wNS0uMjY0LjA0LS4zOTcuMDgtLjI5NC4wNjZMOC45LjQ5NWwtLjA3Mi4wMjgtLjc4My4zMjUtLjAyNy4wMTMtLjU1Mi4yOS0uMjkuMTg2LS4zNjcuMjQ4LS4wMjMuMDE4LS4zMS4yNTMtLjQyMy4zNzItLjE3NC4xNzQtLjIwMi4yMjQtLjE4NS4yMjItLjE2LjIxLS4yMjQuMzMxLS4yMjUuMzcxLS4xNjIuMzA1LS4yMzQuNTE0LS4wNDcuMTEtLjE0Ni40MjgtLjA0NS4xNDYtLjE5Ny44NzUtLjAyOC4xNTQtLjA4Ny44NzYtLjAxMi4yNC0uMDAxLjA4Ni4wMDkuNDAyLjAyLjIzNUw0IDguNWwuMDYyLjMzMi4wNzQuMzA2LjA5NS4zMy4yNS43MDIuMDgyLjIxLjQzMy45MTQuMTUzLjI4Mi41Ljg2LjE5Mi4zMS43IDEuMDMxLjEwMS4xMzYuOTEgMS4xODQuMjk0LjM2NSAxLjA0IDEuMjE0LjIxMy4yMzUuODU2LjkyLjM0LjM1Mi41Ni41NTctLjExMi4wOTQtLjA3LjA2M3EtLjI4Ni4yNjctLjU0LjU2NGE1IDUgMCAwIDAtLjIzMy4yOTdxLS4xNjguMjM0LS4zLjQ5LS4wNjcuMTMzLS4xMi4yNzNhMi41IDIuNSAwIDAgMC0uMTYzLjc0bC0uMDAzLjIyYy4wMDguMzA4LjA3LjYxMi4xODUuOWEyLjUgMi41IDAgMCAwIDEuMDI4IDEuMjE1cS4yNS4xNTIuNTI2LjI0OGEyLjk1IDIuOTUgMCAwIDAgMS4yNDEuMTQxaC4wMDNhMi44IDIuOCAwIDAgMCAxLjAyMy0uMzA0cS4yMDYtLjEwOS4zOS0uMjUzYTIuNSAyLjUgMCAwIDAgLjc5LTEuMDQ4Yy4xMjgtLjMyMi4xOTEtLjY2Ni4xODYtMS4wMTNsLS4wMS0uMTgyYTIuNSAyLjUgMCAwIDAtLjE3LS42OTcgMyAzIDAgMCAwLS4xMzItLjI4NiA0IDQgMCAwIDAtLjMwOS0uNDg3IDUgNSAwIDAgMC0uMTYzLS4yMSA3IDcgMCAwIDAtLjYwMy0uNjMxbC0uMTUxLS4xMy4yNTctLjI1MyAxLjEwMy0xLjE1My4zODItLjQxOS41OTMtLjY2Ny4zODYtLjQ1Mi41NTEtLjY3LjM3Mi0uNDY4LjU0Ny0uNzMxLjI3Ny0uMzc5LjM5LS41ODYuMzI4LS41LjYxNC0xLjA3LjM1My0uNzAyLjAxLS4wMjIuMjY5LS42NTIuMDA5LS4wMjYuMjktLjkwNC4wMy0uMTMyLjEyNy0uNzIuMDI0LS4xOTUuMDA3LS4xMi4wMS0uNDUxLS4wMDQtLjA4NC0uMDIzLS40MDMtLjAyOC0uMzE0LS4xNDMtLjkwNC0uMDA4LS4wMzUtLjE4NC0uNjY5LS4wNjMtLjE4Ni0uMTc5LS40NDQtLjE3LS4zOC0uMDktLjE3NS0uMzAyLS41MS0uMDc3LS4xMi0uMzgtLjUwNi0uMTEyLS4xMjUtLjMyNC0uMzQ4LS4wMi0uMDItLjM4MS0uMzQ3LS4xNTgtLjEzNy0uNTQ3LS40LS4xNS0uMDkyLS40MDItLjIzNi0uMjIzLS4xMTQtLjM1Ni0uMTY4LS4yNDItLjEwMy0uMzA1LS4xMTYtLjI1MS0uMDg2LS4yMjYtLjA2OC0uNzctLjE5LS4wOS0uMDItLjc3Ni0uMTA5LS41ODktLjA1TDEyLjQuMDA5Wm0tLjIzNiAxLjU3NnYxNS41MmwtLjAzOS0uMDcxYTQzIDQzIDAgMCAxLTEuNDI1LTIuODkgMzEgMzEgMCAwIDEtLjk2OC0yLjQyMyAxOSAxOSAwIDAgMS0uNTg0LTEuOTk0IDExIDExIDAgMCAxLS4yNTUtMS42MyA4IDggMCAwIDEtLjAxMy0uNzA1cS4wMDYtLjMwNi4wMjUtLjYxMy4wMy0uNDgxLjEtLjk1OWExMCAxMCAwIDAgMSAuMTQtLjc0NnEuMDY4LS4yOTQuMTU4LS41ODEuMTMtLjQxNS4zMS0uODExLjA2Ny0uMTQzLjE0My0uMjgzYy4zLS41NTUuNzA1LTEuMDY1IDEuMjM4LTEuNDA3YTIuNiAyLjYgMCAwIDEgMS4xNTEtLjQwNnptMS45OTQuMDQgMS4wNDUuMjk3Yy40ODQuMTc5Ljk0OS40MTIgMS4zNzcuNzAyYTUuNSA1LjUgMCAwIDEgMS40ODEgMS40NzggNS41IDUuNSAwIDAgMSAuNTczIDEuMTA0IDYuNSA2LjUgMCAwIDEgLjQgMS43OXEuMDIuMjQxLjAyNC40ODIuMDA2LjIyNS0uMDEuNDUtLjA0NC41MDItLjE4Ny45ODVhOCA4IDAgMCAxLS4yNy43NzcgMTEgMTEgMCAwIDEtLjQzLjkyOCAxOCAxOCAwIDAgMS0xLjE3NyAxLjkzNyAzMCAzMCAwIDAgMS0xLjY5OCAyLjIxNiA0MiA0MiAwIDAgMS0yLjAzNyAyLjI1NiA0MyA0MyAwIDAgMCAxLjM0LTIuNzQxcS4zNDYtLjc3OC42NTItMS41NzEuMzM3LS44NzIuNjA3LTEuNzY2LjIwMy0uNjcuMzUtMS4zNTVBMTEgMTEgMCAwIDAgMTUuOTggOC40cS4wNTEtLjQ5OC4wMzktLjk5OGExNCAxNCAwIDAgMC0uMDIzLS42MTEgMTAuNCAxMC40IDAgMCAwLS40MTMtMi40MiA3IDcgMCAwIDAtLjMzLS44NzJjLS4zMDUtLjY2Ni0uNzMtMS4yODctMS4zMDgtMS43NDFabS0xLjc3NCAxOC40N2guMDQ3bC4wNDQuMDEzcS4wMi4wMTEuMDQuMDI1bC4wMzcuMDM0cS4xMzcuMTI1LjI2NS4yNjEuMDkuMDk2LjE3NC4xOTkuMTA3LjEzLjIuMjcuMDM4LjA2My4wNzMuMTI4LjAzLjA1Ny4wNTQuMTE3LjA0NC4xMDQuMDU1LjIxNmwtLjAwMi4xMzhhLjguOCAwIDAgMS0uMzc2LjYyIDEuMDYgMS4wNiAwIDAgMS0uNDU5LjE1bC0uMTcyLjAwNi0uMTQ0LS4wMTNhMSAxIDAgMCAxLS4yLS4wNDkgMSAxIDAgMCAxLS4xOS0uMDg4bC0uMTEzLS4wODRhLjguOCAwIDAgMS0uMjU4LS40NDJsLS4wMTMtLjA4Ny0uMDA0LS4xMzNhMSAxIDAgMCAxIC4wMTUtLjEwOHEuMDMtLjExNi4wODUtLjIyMy4wNy0uMTM1LjE1OC0uMjU4LjE0OC0uMi4zMTktLjM3OC4xMS0uMTE3LjIyNy0uMjI1bC4wNTUtLjA1MWMuMDM5LS4wMjUuMDM5LS4wMjUuMDgzLS4wMzgiLz48L3N2Zz4=

[flyio-badge-balloon2]: https://img.shields.io/badge/Powered_by_Fly.io-fff?logo=data:image/svg%2bxml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+Rmx5LmlvPC90aXRsZT48cGF0aCBmaWxsPSIjMkExODYzIiBkPSJtMTEuOTkzIDAtLjIxNC4wMDMtLjU0Ny4wMjgtLjI3Ni4wMjUtLjQwNC4wNS0uMjY0LjA0LS4zOTcuMDgtLjI5NC4wNjZMOC45LjQ5NWwtLjA3Mi4wMjgtLjc4My4zMjUtLjAyNy4wMTMtLjU1Mi4yOS0uMjkuMTg2LS4zNjcuMjQ4LS4wMjMuMDE4LS4zMS4yNTMtLjQyMy4zNzItLjE3NC4xNzQtLjIwMi4yMjQtLjE4NS4yMjItLjE2LjIxLS4yMjQuMzMxLS4yMjUuMzcxLS4xNjIuMzA1LS4yMzQuNTE0LS4wNDcuMTEtLjE0Ni40MjgtLjA0NS4xNDYtLjE5Ny44NzUtLjAyOC4xNTQtLjA4Ny44NzYtLjAxMi4yNC0uMDAxLjA4Ni4wMDkuNDAyLjAyLjIzNUw0IDguNWwuMDYyLjMzMi4wNzQuMzA2LjA5NS4zMy4yNS43MDIuMDgyLjIxLjQzMy45MTQuMTUzLjI4Mi41Ljg2LjE5Mi4zMS43IDEuMDMxLjEwMS4xMzYuOTEgMS4xODQuMjk0LjM2NSAxLjA0IDEuMjE0LjIxMy4yMzUuODU2LjkyLjM0LjM1Mi41Ni41NTctLjExMi4wOTQtLjA3LjA2M3EtLjI4Ni4yNjctLjU0LjU2NGE1IDUgMCAwIDAtLjIzMy4yOTdxLS4xNjguMjM0LS4zLjQ5LS4wNjcuMTMzLS4xMi4yNzNhMi41IDIuNSAwIDAgMC0uMTYzLjc0bC0uMDAzLjIyYy4wMDguMzA4LjA3LjYxMi4xODUuOWEyLjUgMi41IDAgMCAwIDEuMDI4IDEuMjE1cS4yNS4xNTIuNTI2LjI0OGEyLjk1IDIuOTUgMCAwIDAgMS4yNDEuMTQxaC4wMDNhMi44IDIuOCAwIDAgMCAxLjAyMy0uMzA0cS4yMDYtLjEwOS4zOS0uMjUzYTIuNSAyLjUgMCAwIDAgLjc5LTEuMDQ4Yy4xMjgtLjMyMi4xOTEtLjY2Ni4xODYtMS4wMTNsLS4wMS0uMTgyYTIuNSAyLjUgMCAwIDAtLjE3LS42OTcgMyAzIDAgMCAwLS4xMzItLjI4NiA0IDQgMCAwIDAtLjMwOS0uNDg3IDUgNSAwIDAgMC0uMTYzLS4yMSA3IDcgMCAwIDAtLjYwMy0uNjMxbC0uMTUxLS4xMy4yNTctLjI1MyAxLjEwMy0xLjE1My4zODItLjQxOS41OTMtLjY2Ny4zODYtLjQ1Mi41NTEtLjY3LjM3Mi0uNDY4LjU0Ny0uNzMxLjI3Ny0uMzc5LjM5LS41ODYuMzI4LS41LjYxNC0xLjA3LjM1My0uNzAyLjAxLS4wMjIuMjY5LS42NTIuMDA5LS4wMjYuMjktLjkwNC4wMy0uMTMyLjEyNy0uNzIuMDI0LS4xOTUuMDA3LS4xMi4wMS0uNDUxLS4wMDQtLjA4NC0uMDIzLS40MDMtLjAyOC0uMzE0LS4xNDMtLjkwNC0uMDA4LS4wMzUtLjE4NC0uNjY5LS4wNjMtLjE4Ni0uMTc5LS40NDQtLjE3LS4zOC0uMDktLjE3NS0uMzAyLS41MS0uMDc3LS4xMi0uMzgtLjUwNi0uMTEyLS4xMjUtLjMyNC0uMzQ4LS4wMi0uMDItLjM4MS0uMzQ3LS4xNTgtLjEzNy0uNTQ3LS40LS4xNS0uMDkyLS40MDItLjIzNi0uMjIzLS4xMTQtLjM1Ni0uMTY4LS4yNDItLjEwMy0uMzA1LS4xMTYtLjI1MS0uMDg2LS4yMjYtLjA2OC0uNzctLjE5LS4wOS0uMDItLjc3Ni0uMTA5LS41ODktLjA1TDEyLjQuMDA5Wm0tLjIzNiAxLjU3NnYxNS41MmwtLjAzOS0uMDcxYTQzIDQzIDAgMCAxLTEuNDI1LTIuODkgMzEgMzEgMCAwIDEtLjk2OC0yLjQyMyAxOSAxOSAwIDAgMS0uNTg0LTEuOTk0IDExIDExIDAgMCAxLS4yNTUtMS42MyA4IDggMCAwIDEtLjAxMy0uNzA1cS4wMDYtLjMwNi4wMjUtLjYxMy4wMy0uNDgxLjEtLjk1OWExMCAxMCAwIDAgMSAuMTQtLjc0NnEuMDY4LS4yOTQuMTU4LS41ODEuMTMtLjQxNS4zMS0uODExLjA2Ny0uMTQzLjE0My0uMjgzYy4zLS41NTUuNzA1LTEuMDY1IDEuMjM4LTEuNDA3YTIuNiAyLjYgMCAwIDEgMS4xNTEtLjQwNnptMS45OTQuMDQgMS4wNDUuMjk3Yy40ODQuMTc5Ljk0OS40MTIgMS4zNzcuNzAyYTUuNSA1LjUgMCAwIDEgMS40ODEgMS40NzggNS41IDUuNSAwIDAgMSAuNTczIDEuMTA0IDYuNSA2LjUgMCAwIDEgLjQgMS43OXEuMDIuMjQxLjAyNC40ODIuMDA2LjIyNS0uMDEuNDUtLjA0NC41MDItLjE4Ny45ODVhOCA4IDAgMCAxLS4yNy43NzcgMTEgMTEgMCAwIDEtLjQzLjkyOCAxOCAxOCAwIDAgMS0xLjE3NyAxLjkzNyAzMCAzMCAwIDAgMS0xLjY5OCAyLjIxNiA0MiA0MiAwIDAgMS0yLjAzNyAyLjI1NiA0MyA0MyAwIDAgMCAxLjM0LTIuNzQxcS4zNDYtLjc3OC42NTItMS41NzEuMzM3LS44NzIuNjA3LTEuNzY2LjIwMy0uNjcuMzUtMS4zNTVBMTEgMTEgMCAwIDAgMTUuOTggOC40cS4wNTEtLjQ5OC4wMzktLjk5OGExNCAxNCAwIDAgMC0uMDIzLS42MTEgMTAuNCAxMC40IDAgMCAwLS40MTMtMi40MiA3IDcgMCAwIDAtLjMzLS44NzJjLS4zMDUtLjY2Ni0uNzMtMS4yODctMS4zMDgtMS43NDFabS0xLjc3NCAxOC40N2guMDQ3bC4wNDQuMDEzcS4wMi4wMTEuMDQuMDI1bC4wMzcuMDM0cS4xMzcuMTI1LjI2NS4yNjEuMDkuMDk2LjE3NC4xOTkuMTA3LjEzLjIuMjcuMDM4LjA2My4wNzMuMTI4LjAzLjA1Ny4wNTQuMTE3LjA0NC4xMDQuMDU1LjIxNmwtLjAwMi4xMzhhLjguOCAwIDAgMS0uMzc2LjYyIDEuMDYgMS4wNiAwIDAgMS0uNDU5LjE1bC0uMTcyLjAwNi0uMTQ0LS4wMTNhMSAxIDAgMCAxLS4yLS4wNDkgMSAxIDAgMCAxLS4xOS0uMDg4bC0uMTEzLS4wODRhLjguOCAwIDAgMS0uMjU4LS40NDJsLS4wMTMtLjA4Ny0uMDA0LS4xMzNhMSAxIDAgMCAxIC4wMTUtLjEwOHEuMDMtLjExNi4wODUtLjIyMy4wNy0uMTM1LjE1OC0uMjU4LjE0OC0uMi4zMTktLjM3OC4xMS0uMTE3LjIyNy0uMjI1bC4wNTUtLjA1MWMuMDM5LS4wMjUuMDM5LS4wMjUuMDgzLS4wMzgiLz48L3N2Zz4=

**Comment by enstyled** [comment]
Hello @LitoMore, thank you for adding the Fly.io logo to shields.io 😊 Technically the first (full logo) version is more correct, but the simplified is definitely more readable, especially the dark on light version.

Let me consult with the team and we can get back to you about this!

**Comment by enstyled** [comment]
Confirmed with the team, let's go with the more legible version with the balloon only - 2nd and 3rd attachments above 👍🏼

**Comment by andie787** [comment]
completed

**Comment by LitoMore** [comment]
Hi, team. Are you happy with the tiny differences in this icon?

See https://github.com/simple-icons/simple-icons/pull/11025#pullrequestreview-2104341500

**Comment by enstyled** [comment]
@LitoMore I believe it's ok 👍🏼😊 Thank you for checking in!
