### ISSUE TITLE
Issue with the "Automatically stop and start Machines" doc default values

### ISSUE THREAD

**Issue by prondubuisi** [superfly/docs#1595]
I found an issue with this document.

Title: Automatically stop and start Machines
Location: https://fly.io/docs/apps/autostart-stop/
Source: https://github.com/superfly/docs/blob/main/apps/autostart-stop.html.markerb

### Describe the issue

In the Default Value section, the default value for auto_stop_machines = false
>The default settings for apps that don’t specify any auto start and stop settings in fly.toml are auto_start_machines = true and auto_stop_machines = false.

In the fly.toml snippet the value is set to true 
![CleanShot 2024-06-19 at 15 31 06@2x](https://github.com/superfly/docs/assets/22311928/c018f061-9961-4cb3-a692-e98ed103472d)

### Addtional info
I added a potential fix [here ](https://github.com/superfly/docs/pull/1596)

**Comment by andie787** [comment]
Hi @prondubuisi 

There are 2 different set of default values here. The values that are applied when you don't specify any settings in the `fly.toml` file. And then the default settings in the `fly.toml` file when you create your app with `fly launch`.

We could make this more clear! We'll update this doc soon!
