### ISSUE TITLE
Issue with the "Run a Flask App" doc

### ISSUE THREAD

**Issue by josenvg36** [superfly/docs#1610]
I found an issue with this document.

Title: Run a Flask App
Location: https://fly.io/docs/python/frameworks/flask/
Source: https://github.com/superfly/docs/blob/main/python/frameworks/flask.html.markerb

### Describe the issue

I was running the Run a Flask App tutorial (https://fly.io/docs/python/frameworks/flask/), everything was running fine until the last step, when deploying fly i received this error '''Error: failed to fetch an image or build from source: app does not have a Dockerfile or buildpacks configured.'''

**Comment by fliepeltje** [comment]
hey! To clarify, did you run through the "build a flask app from scratch" or through the "speedrun"? 

In addition:
- did you try re-running `fly launch`?
- if so, could you specify which OS you are on?

Thanks for reporting! :)

**Comment by zanchey** [comment]
Having just run through this - I did the "build a flask app from scratch" steps and it worked fine, on macOS.

**Comment by fliepeltje** [comment]
@josenvg36 I will close this issue; if you are still having problems, please re-open it and provide the details as described above; thanks!
