### ISSUE TITLE
Organise flyctl sidebar nav for quick scanning

### ISSUE THREAD

**Issue by catflydotio** [superfly/docs#168]
Things we can do:

- Standardise the labels, and put them in alphabetical order
- Put the actual commands in the sidebar to help people get familiar with what's there. I know that used to be there, and it helped me a lot. If we use `fly` instead of `flyctl` it'll fit better; perhaps that will mitigate the reason they were removed?

**Comment by jsierles** [comment]
Commands in the main sidebar?

**Comment by catflydotio** [comment]
Ohai @jsierles ! The flyctl nav used to have the form "short description    command name" on every line. Now it's only descriptions (the descriptions are desperate for some sort of harmonisation too). I can never find anything and I already know more or less what should be there. Having the command name in there helps with scanning and parsing.

**Comment by catflydotio** [comment]
Mitigated with https://github.com/superfly/docs/commit/1fee838570c80ab94697aba754036919a1639d94 which adds the actual commands to the flyctl nav. Descriptions could still use improvement

**Comment by andie787** [comment]
stale issue - closing
