### ISSUE TITLE
Issue with the "Run a Go App" doc

### ISSUE THREAD

**Issue by LA** [superfly/docs#1719]
I found an issue with this document.

Title: Run a Go App
Location: https://fly.io/docs/languages-and-frameworks/golang/
Source: https://github.com/superfly/docs/blob/main/languages-and-frameworks/golang.html.markerb

#### This text in the notice at the top of the page:
> It’s simple, it’s scalable, it’s secure—it’s your bucket in the cloud with effortless CDN-magic. It’s easy to integrate with Go, [try it out](https://fly.io/docs/languages-and-frameworks/golang/docs/languages-and-frameworks/golang/#add-tigris-global-storage-optional).

#### The `try it out` button links to a 404 page:
- https://fly.io/docs/languages-and-frameworks/golang/docs/languages-and-frameworks/golang/#add-tigris-global-storage-optional (Notice the repeat path).

https://github.com/superfly/docs/blob/005ac199c198c315d68127bf36692f86da72e3ed/languages-and-frameworks/golang.html.markerb#L12

#### Proposed Solution:
```diff
+ [try it out](#add-tigris-global-storage-optional)
- [try it out](docs/languages-and-frameworks/golang/#add-tigris-global-storage-optional)
```

### Addtional info

<img width="802" alt="Screenshot 2024-07-25 at 20 41 43" src="https://github.com/user-attachments/assets/b6cf47f6-b838-4618-8cbe-99c64ffd65f5">

**Comment by andie787** [comment]
fixed by #1721 

thanks for letting us know @LA !
