### ISSUE TITLE
Issue with the "Fly.io and Open Source" doc

### ISSUE THREAD

**Issue by george-grec** [superfly/docs#1736]
I found an issue with this document.

Title: Fly.io and Open Source
Location: https://fly.io/docs/about/open-source/
Source: https://github.com/superfly/docs/blob/main/about/open-source.html.markerb

### Describe the issue

It seems that the section "Recurring donations", unfortunately, is not correct anymore. I don't know if this has been brought to the attention of the fly.io team but apparently due to an upgrade to GitHub Enterprise all sponsorships have been canceled.

<img width="789" alt="image" src="https://github.com/user-attachments/assets/4d2c9a66-f846-47ef-a8d6-1586855832ba">

Personally, I think these kinds of sponsorships are a great way to support the open-source community and their work which we all depend and build on. Sponsorships are a great marketing tool as well, me and many others have been made aware of fly.io by their sponsorship of the Gleam programming language, for example. My ask would be for the team at fly.io to reinstate the sponsorships to keep the ecosystem successful and thriving - thank you in advance!

**Comment by SnakeDoc** [comment]
I, for one, had never heard of Fly.io before joining the Gleam community. I'm sad to see their sponsorship go :(

**Comment by andie787** [comment]
Thank for bringing this up and yes we did notice! We're working on getting sponsorships sorted out as soon as possible.

**Comment by inoas** [comment]
I never heard of them either, despite being an Elixir user, but if I ever run a gleam app I will try/use fly.io first and if happy, stay there.

**Comment by george-grec** [comment]
this has been resolved :) thank you fly.io!
