### ISSUE TITLE
Issue with the "Run a FastAPI app" doc + "fastapi-cli" missed

### ISSUE THREAD

**Issue by icehongssii** [superfly/docs#1738]
I found an issue with this document.

Title: Run a FastAPI app
Location: https://fly.io/docs/python/frameworks/fastapi/
Source: https://github.com/superfly/docs/blob/main/python/frameworks/fastapi.html.markerb

### Describe the issue

The official doc said `We can then serve the development version of the app using the fastapi cli tool - fastapi run`.
But the doc has never mentioned installing fastapi-cli.
Thus,  `poetry add fastapi`has to include `fastapi-cli`

```
poetry add fastapi fastapi-cli
```

### Addtional info

![image](https://github.com/user-attachments/assets/fdbb2039-0fb3-408e-b45c-64af1443ec7c)

**Comment by andie787** [comment]
I think the other option is to run `poetry add "fastapi[standard]"`. 
@fliepeltje what is your preference?

**Comment by fliepeltje** [comment]
This has changed in the most recent version of FastAPI; they've changed to not include the CLI by default, so yeah we should update it. Thanks for catching it!
