### ISSUE TITLE
Issue with the "Backup, Restores, & Snapshots" doc -- Snapshot Restores

### ISSUE THREAD

**Issue by swilson-fly** [superfly/docs#1772]
I found an issue with this document.

Title: Backup, Restores, & Snapshots
Location: https://fly.io/docs/postgres/managing/backup-and-restore/
Source: https://github.com/superfly/docs/blob/main/postgres/managing/backup-and-restore.html.markerb

### Describe the issue

There's some interop issues with restoring a snapshot for an older stolon PG into a new postgres-flex cluster. It's possible there's issues restoring to diff pg-flex major versions as well! Restoring to the same image is best, but looks like there's some pg-flex versions that are more compatible than others. Ref: https://community.fly.io/t/reuse-old-volume-in-new-machine-after-irrepairable-hardware-damage/21230/34

### Addtional info

Todo: add guidance for specifying images.

**Comment by AshitaGK** [comment]
Hi @swilson-fly,
By restoring a snapshot to the new pg-cluster based on the pg-flex versions, do you mean appending `--image-ref` to fly postgres create --snapshot-id <snapshot-id>
command?

**Comment by swilson-fly** [comment]
@AshitaGK Yes, exactly! By default `fly postgres create` makes a new cluster running postgres-flex:16. For snapshots from clusters running older versions this may not be compatible, so users need to specify the same image as their original cluster. 

PR for a doc fix is here and will be shipped today https://github.com/superfly/docs/pull/1799
