### ISSUE TITLE
Equivalent values of Auto Stop Machines

### ISSUE THREAD

**Issue by AshitaGK** [superfly/docs#1775]
Title: Equating previous values to the current value of auto_stop_machines

Location: https://fly.io/docs/launch/autostop-autostart/#stop-a-machine-by-terminating-its-main-process

**Mention equivalent values in Autostart/Autostop doc**
The previous values assigned to auto_stop_machines used to be true and false.
Mention  within auto_stop_machines settings that false equates to "**off**" and true equates to "**stop**"

This would probably clear some confusion for people who had earlier set up according to those values as mentioned in this guide :
https://community.fly.io/t/autosuspend-is-here-machine-suspension-is-enabled-everywhere/20942

**Comment by andie787** [comment]
Great idea!
