### ISSUE TITLE
Why are fly.io/docs pages content duplicated?

### ISSUE THREAD

**Issue by Pedromigacz** [superfly/docs#1781]
**Link to the affected page or pages**
[Dockerfile website page](https://fly.io/docs/js/the-basics/dockerfiles/)
[Dockerfile github file](https://github.com/superfly/docs/blob/main/js/the-basics/dockerfiles.html.md)

**Describe what part of the site needs improvement**
The content on github md files is correct, but it's rendered duplicated on the actual website

**Additional info**
This is happening both on Firefox and Chrome

![image](https://github.com/user-attachments/assets/9c87379a-bbf0-4d0b-86b5-7b2157445d09)

**Comment by AshitaGK** [comment]
I've noticed this under guides for different languages and frameworks too. @andie787 can you check this out?

**Comment by andie787** [comment]
All fixed!
