### ISSUE TITLE
UI glitch in header

### ISSUE THREAD

**Issue by theodoregold** [superfly/docs#181]
I was checking that beautiful gradient on fly.io in dev tools, but noticed there is a bug with it on mobile. It seems like `position: relative` is missing on `header` tag.

<img width="450" alt="Screenshot 2022-06-21 at 20 32 23" src="https://user-images.githubusercontent.com/1449114/174862296-f2115b4d-d6fc-44f4-9bb1-0943c84fea2d.png">

**Comment by hkfoster** [comment]
Fixed earlier today. Thanks for the heads up!
