### ISSUE TITLE
minio guide issues

### ISSUE THREAD

**Issue by aphillipo** [superfly/docs#207]
I would have just made a PR but not sure where the actual files for this reside, I just see a reference somewhere else `<%= github_render("fly-examples/appkata-minio/main/README.md") %>`, did a search in the fly org and got nothing 🤷🏻‍♂️

Anyway, the link to Private Networking in the MinIO guide is incorrect, should be /private-networking not /privatenetworking 👍🏻

Additionally it seems not possible to host MinIO on a shared instance, it crashes as soon as you login with out of memory errors; might be an idea to highlight this or find an alternative that is less memory intensive.

**Comment by aphillipo** [comment]
Is there a solution for hosting images yet that works like s3? It's a big deal if there isn't something sensible, I suppose I could just use a real s3 bucket but it would better to have all the basics done within fly.

**Comment by jsierles** [comment]
Storage is tricky - it's not likely something Fly will offer any time soon as a hosted service. S3 works pretty well. But if you like playing with tools like Minio, Fly is a great place to do it!
