### ISSUE TITLE
Request to add Fly.io to Paketo adopter's list

### ISSUE THREAD

**Issue by davidmirror-ops** [superfly/docs#249]
Hi Fly.io community:

I'm the OSS Community Manager for Paketo Buildpacks, and we found some references to our project in your docs (like [here](https://fly.io/docs/reference/builders/#buildpacks))

That is great and we wanted to confirm if it's okay that we add you (or you add yourselves) to the Paketo [adopter's list ](https://github.com/paketo-buildpacks/community/blob/main/ADOPTERS.md)sharing your use case with this community

In any case, we work to keep improving the project and any feedback in that regard is most than welcome

Thanks!

**Comment by jsierles** [comment]
Thanks for getting in touch. We haven't adopted Paketo buildpacks directly into our system. Rather, we mention it as one of many buildpack options available for use. That said, we have no problem with being added to your adopter list as long as there's no expectation to directly support Paketo buildpacks from our side.
