### ISSUE TITLE
Sidekiq guide expects REDIS_URL, but Redis setup created FLY_REDIS_CACHE_URL

### ISSUE THREAD

**Issue by radamanthus** [superfly/docs#262]
The [Sidekiq guide](https://fly.io/docs/rails/the-basics/sidekiq/) expects an environment variable named `REDIS_URL` . I followed the [Redis setup guide](https://fly.io/docs/reference/redis/), but it defined `FLY_REDIS_CACHE_URL` not `REDIS_URL` .

**Comment by jsierles** [comment]
Hey! Sorry for the confusion. `FLY_REDIS_CACHE_URL` is deprecated. For the new Redis service, you'll need to set `REDIS_URL` yourself like: `fly secrets set REDIS_URL=redis://`. You can find the correct URL with `fly redis status <id>`

**Comment by radamanthus** [comment]
Ahh, it's up to me to define the REDIS_URL env var. 

Thanks!

**Comment by jsierles** [comment]
Yes - soon you'll be able to use `flyctl redis attach` to make it a bit easier.

**Comment by radamanthus** [comment]
:sweat_smile: Ahhh I skimmed the doc and missed this, sorry!
> Be sure to set the REDIS_URL via a secret as demonstrated in the [Redis documentation](https://fly.io/docs/rails/the-basics/sidekiq/reference/redis/#access-from-other-fly-applications-via-redis_url).
