### ISSUE TITLE
Github Action: Continuous Deployment Documentation

### ISSUE THREAD

**Issue by graciasc** [superfly/docs#300]
**Update Documentation**
Link: [continous-deployment-docs](https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/)

**Details**
`Step 7` should be updated to `flyctl launch` command instead of `flyctl apps create` as it no longer creates a `fly.toml` file which is stated here [Link](https://fly.io/docs/flyctl/apps-create/)

**Comment by catflydotio** [comment]
Thanks, @graciasc. Finally changed this.
