### ISSUE TITLE
Heroku database migration has a few bugs

### ISSUE THREAD

**Issue by miketheman** [superfly/docs#305]
Specifically, where to run the `psql` command, as it likely needs to be run within an application context, and what state the database should be in.

There's also issues with trying to restore Heroku's `GRANT`s that might be overcome with:

`pg_dump --no-owner --no-privileges -C -d $HEROKU_DATABASE_URL | psql -d $DATABASE_URL`

Also notable, the `$HEROKU_DATABASE_URL` ends with a database name, so the inbound database will be named something weird that doesn't map to the `$DATABASE_URL`

**Comment by s2k** [comment]
Especially since Heroku announced the end of the support of the free tiers, I’d find it incredibly helpful, if there were a working migration doc.

**Comment by bradgessler** [comment]
For posterity, migration docs for Rails apps are at https://fly.io/docs/rails/getting-started/migrate-from-heroku/ and moving a PG database at https://fly.io/docs/postgres/getting-started/migrate-from-heroku/
