### ISSUE TITLE
Many of the Speedrun links 404

### ISSUE THREAD

**Issue by mtlynch** [superfly/docs#324]
On the [Speedrun page](https://fly.io/docs/speedrun/), many of the links now 404, e.g.,:

* https://fly.io/docs/getting-started/crystal/
* https://fly.io/docs/getting-started/node/
* https://fly.io/docs/getting-started/python/
* https://fly.io/docs/getting-started/redwood/

**Comment by catflydotio** [comment]
Hopefully properly fixed with 33eef2982f. Thanks!

**Comment by mtlynch** [comment]
Thanks so much for the quick turnaround, @catflydotio!
