### ISSUE TITLE
Vm sizes need to include Machine specific sizes

### ISSUE THREAD

**Issue by davissp14** [superfly/docs#374]
We have vm-sizes that are specific to Machines that need to be documented.

```
shared-cpu-1x - 256MB
shared-cpu-2x - 4GB
shared-cpu-4x - 8GB
shared-cpu-8x - 16GB
```

https://fly.io/docs/reference/scaling/#viewing-available-vm-sizes

**Comment by andie787** [comment]
This is out of date now. The link is to a doc that's legacy now, and we don't display the output of `fly platform vm-sizes` anywhere else (probably to avoid maintenance when it changes).
