### ISSUE TITLE
Document how to bootstrap a database from a file (e.g. using pg_restore)

### ISSUE THREAD

**Issue by wmakley** [superfly/docs#437]
Basically, I often have a .sql or .dump file (binary backup from pg_dump) that I need to load to bootstrap an application. I am having trouble figuring out how to do this. I have first followed the instructions to create a new Rails app, and am now reviewing the postgres documentation since the Rails app tutorial didn't cover this.

- I can proxy a local port to the DB container (seems very useful!).
- I cannot access my database password or connection details, so I cannot actually do anything.
- ???

I'm sure there is a workaround, like I can run a command in my app container to dump the secrets so I can connect, but I would just like a sequence of steps I can follow to load the data and be done.

**Comment by fideloper** [comment]
Hi! I can see the appeal of asking this in the docs, but please ask in the community forums - you’ll get a better and faster response! https://community.fly.io/
