### ISSUE TITLE
SQLite3 guide for Rails

### ISSUE THREAD

**Issue by rob-mccormick** [superfly/docs#490]
Hi,

I completed the Starter Rails App, and then wanted to convert to an SQLite3 database. 

In the SQLite3 guide (in "Rails on Fly"), the last step updates the file `lib/tasks/fly.rake` by moving the dependency on the `db:migrate` task from the `release` to `server`. In the line for the server (`task :server => 'db:migrate' do`) it removes the reference to the `:swapfile` that was there from the Starter Rails App.

It's unclear - what does the `:swapfile` do, and is it correct to remove reference to the `:swapfile` in the `server` task?

Clarification would be helpful.

**Comment by rubys** [comment]
Rails support has been completely redone.

Documentation for sqlite3: https://fly.io/docs/rails/getting-started/dockerfiles/#using-sqlite3

Documentation for dealing with out of memory situations, including adding a swapfile: https://fly.io/docs/rails/getting-started/dockerfiles/#out-of-memory
