### ISSUE TITLE
[Rails] Update Getting Started Guide

### ISSUE THREAD

**Issue by Naokimi** [superfly/docs#524]
When following the [Getting Started](https://fly.io/docs/rails/getting-started/) guide for Rails I get asked the following the running `fly launch`:
```
? Would you like to set up an Upstash Redis database now? 
```
But this step is not recorded in the documentation (adding Redis comes in the documentation after Scaffolding as a separate step).

**Comment by rubys** [comment]
Fixed: https://fly.io/docs/rails/getting-started/.  Thanks!
