### ISSUE TITLE
No documentation for Rust

### ISSUE THREAD

**Issue by jeffersonataide** [superfly/docs#530]
There is no documentation for Rust in `Language & Framework Guides`, instead the link in the home page points to `https://fly.io/docs/speedrun/`

**Comment by sachinrao8312** [comment]
@jsierles  @jeregrine Please assign this issue to me

**Comment by andie787** [comment]
It's true, we don't have any docs for Rust despite using it ourselves. :) But if there was a link that went nowhere, it's been removed. Closing.
