### ISSUE TITLE
flyctl restart - deprecated

### ISSUE THREAD

**Issue by Bunmi194** [superfly/docs#551]
The flyctl restart [APPNAME] [flags] command has been deprecated and no longer works in the CLI . 

![Screen Shot 2023-01-23 at 5 22 32 PM](https://user-images.githubusercontent.com/106192417/214093250-61fd6248-a7aa-4ac4-b160-16b6ffa5c3bd.png)

The new command to restart an existing app is: fly apps restart [APPNAME] [flags]

So flyctl restart [APPNAME] [flags] should be replaced with fly apps restart [APPNAME] [flags] in the documentation on https://fly.io/docs/flyctl/restart/

**Comment by vielmetti** [comment]
Ran into this today.

**Comment by andie787** [comment]
as mentioned, fixed by https://github.com/superfly/flyctl/pull/1813
