### ISSUE TITLE
Mentioned  repository is not available, "https://github.com/fly-apps/hello-gunicorn-flask"

### ISSUE THREAD

**Issue by angordeyev** [superfly/docs#557]
The repository is mentioned but not accessible, probably it is private for Fly.io organization.

https://github.com/superfly/docs/blob/49d21adc07c48d0a38778a4bb53f71c3e7238f88/machines/guides-examples/machines-app-using-flyctl.html.md.erb#L63

**Comment by catflydotio** [comment]
Ha! Thank you, @angordeyev. It's public now.
