### ISSUE TITLE
mention `fly` alias in flyctl install doc.

### ISSUE THREAD

**Issue by catflydotio** [superfly/docs#559]
Our scripts add a system symlink from `flyctl` to `fly`. See #555

**Comment by ferringb** [comment]
Just confirming, it's desired that the docs refer to `flyctl` rather than `fly` ?

If so, this bit of horribleness (and manual review) does the bulk of it:
```
flyctl -h | sed -ne '0,/Deploy/d' -e '/^  .*/p' -e '/Flags/q' | \
  awk '{print "s/fly "$1" /flyctl "$1" /g";}' \
  > patterns
find . -type f \! -wholename '*/.git/*' -print0 | \
  xargs -0 -n1 -P10  sed -f patterns -i
rm patterns
```
