### ISSUE TITLE
Unrendered partial shown in nginx proxy docs

### ISSUE THREAD

**Issue by skovati** [superfly/docs#578]
Just a small error I found while searching through the docs. Looks like some embedded Ruby templating got included in `.md` files which doesn't get processed.

![image](https://user-images.githubusercontent.com/49844593/217059507-1be6a40d-bc53-4b6f-9564-9d7394a9fad8.png)

Based on a [quick search](https://github.com/superfly/docs/search?l=Markdown&q=%3C%25%3D+partial+%22%2Fdocs%2Fpartials%2Fobsolete_doc%22+%25%3E), it looks like this issues exists in one more `md` doc.

[https://fly.io/docs/app-guides/global-nginx-proxy/](https://fly.io/docs/app-guides/global-nginx-proxy/)
[https://fly.io/docs/app-guides/graphql-on-fly-with-hasura/](https://fly.io/docs/app-guides/graphql-on-fly-with-hasura/)

**Comment by bradgessler** [comment]
https://github.com/superfly/docs/commit/06a0e9f98da42b16f490cad6760180c9c7f6ed09 fixes this issue.

Note for future devs: when this happens in Middleman, append `.erb` at the end of the file if its not already there so that the file gets processed by erb.
