### ISSUE TITLE
Docs for Rails Console seem to be out of date

### ISSUE THREAD

**Issue by rustyameadows** [superfly/docs#604]
On the Rails ["Running Tasks & Consoles" page](https://fly.io/docs/rails/the-basics/run-tasks-and-consoles/) the commands given point to a folder location that does not align with my new deployment. 

The docs suggest
```fly ssh console -C "app/bin/rails console"```

I get an error of 
```"fork/exec app/bin/rails: no such file or directory"```

While this works for me:

```fly ssh console -C "rails/bin/rails console"```

It seems that new deployments have moved to a new file structure...

Is this something unique to my deployment or should the docs be updated?

**Comment by rubys** [comment]
Fixed.  Thanks!

**Comment by pawlarius** [comment]
This command no longer works.. 
```
fly ssh console -C "rails/bin/rails console"
Connecting to - ... complete
fork/exec rails/bin/rails: no such file or directory
Error: ssh shell: wait: remote command exited without exit status or exit signal
```

I checked the docs https://fly.io/docs/rails/the-basics/run-tasks-and-consoles/ seems like it changed into
`fly ssh console --pty -C "/rails/bin/rails console"`

But this also doesn't work anymore..
```
Connecting to - ... complete
fork/exec rails/bin/rails: no such file or directory
Error: ssh shell: wait: remote command exited without exit status or exit signal
```
