### ISSUE TITLE
Broken link on https://fly.io/docs/litefs/mount/

### ISSUE THREAD

**Issue by teodorlu** [superfly/docs#611]
Hi!

From, [/mount/][mount], I can click a link to **litefs.yml config file**. I'm sent to `https://fly.io/docs/litefs/mount/config`, which doesn't appear to exist. As far as I can tell, the right url is `https://fly.io/docs/litefs/config/`.

Unrelated, I'm really excited about LiteFS!

[mount]: https://fly.io/docs/litefs/mount/

**Comment by benbjohnson** [comment]
@teodorlu Thanks for letting me know! I posted a fix on #612. I'll merge it once CI is 🍏
