### ISSUE TITLE
"Edit this page" link not visible on mobile

### ISSUE THREAD

**Issue by AustinWise** [superfly/docs#618]
Currently the "Edit this page" button at the bottom of the documentation pages is not visible on mobile devices. You can simulate this problem on desktop by resizing your browser window to be very narrow.

Looking at the CSS rules in my web browser's dev tools, it looks like the link is hidden by default. A `.md\:block` rule makes the link visible when the page is wide enough with a  `@media (min-width: 768px)` selector.

Personally it would be helpful to have this link visible on mobile devices, if only so I have a better idea where to file bugs about documentation.

**Comment by AustinWise** [comment]
This was the particular page I noticed I could not the "edit this page" at the bottom:

https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

**Comment by Steph-crown** [comment]
Has this issue been worked on?

**Comment by andie787** [comment]
fixed by the amazing @hkfoster !

**Comment by AustinWise** [comment]
Thanks! I checked and it now works as expected.
