### ISSUE TITLE
 Document the Fly log shipper

### ISSUE THREAD

**Issue by jsierles** [superfly/docs#63]
This includes:

* Moving the README to our site
* Linking the repo back to our site (what we want to do with ALL repos)

Also, these docs should specify how to run the shipper directly from a [the Docker image](https://hub.docker.com/repository/docker/flyio/log-shipper), without having to setup a `fly.toml` or clone the repo.

**Comment by catflydotio** [comment]
Have this now: https://fly.io/docs/going-to-production/monitoring/exporting-logs/#the-fly-log-shipper

**Comment by andie787** [comment]
This is done https://fly.io/docs/metrics-and-logs/exporting-logs/
