### ISSUE TITLE
Docs for running periodic jobs

### ISSUE THREAD

**Issue by jsierles** [superfly/docs#64]
We have nothing built-in for running periodic jobs. People ask a lot because other platforms offer it. But we can still guide people.

We have a [simple example](https://github.com/aptible/supercronic) on how to run cron jobs. But it's not that useful on its own. It would be useful for those willing to add it to Dockerfile.

We should hat-tip to other good job tools like:
* sidekiq-cron (Ruby)
* node-cron (node)
* oban (elixir)

These tools could be documented more extensively on runtime-specific doc pages.

**Comment by catflydotio** [comment]
I'm closing this issue for Docs because it's framework-specific.

**Comment by bradgessler** [comment]
I wrote a framework agnostic guide for cron at https://fly.io/docs/app-guides/supercronic/

**Comment by catflydotio** [comment]
Even better. Closed as actually completed :)
