### ISSUE TITLE
Docs only refers to Postgres Flex by default

### ISSUE THREAD

**Issue by guillaumervls** [superfly/docs#648]
[Postgres Flex](https://github.com/fly-apps/postgres-flex) is what we deploy by default now. We should remove or mark as legacy mentions to [our old Postgres setup](https://github.com/fly-apps/postgres-ha).

We should maybe also update [our PG blog post](https://fly.io/blog/how-we-built-fly-postgres/).

**Comment by redjonzaci** [comment]
There are 4 mentions in the blog post, but the link [Running Locally (for Fly Employees)](https://github.com/superfly/docs#running-locally-for-fly-employees) is broken.

**Comment by andie787** [comment]
I would say this is done done now
