### ISSUE TITLE
Mention secrets import in v2 doc?

### ISSUE THREAD

**Issue by sb8244** [superfly/docs#650]
https://github.com/superfly/docs/edit/main/apps/migrate-to-v2.html.md

It may be worth mentioning that `fly secrets import` exists to bulk import a set of ENV. This is ideal for the migration actually, because there may be a lot of secrets.

**Comment by jsierles** [comment]
Thanks, that's a good idea. I've used a script in the past to clone secrets across apps: https://gist.github.com/jsierles/fa7208e07decc59a37ac789d2fb505aa

**Comment by catflydotio** [comment]
Thanks @sb8244, and @jsierles. Added the script to the doc.

https://github.com/superfly/docs/commit/f8542fefc92417de5957c062eade6f099850e55b
