### ISSUE TITLE
Clarify how to set runtime versus build-time variables

### ISSUE THREAD

**Issue by jsierles** [superfly/docs#66]
Even _we_ get confused about this. It should be clear how to set both of these for Dockerfile and buildpack deployments.

Also it should be clear that secrets are not available at build time. For example, a remote builder technically *can* reach a database, but the DATABASE_URL is not available to the builder without passing it in as a build argument.

**Comment by andie787** [comment]
Covered by https://fly.io/docs/reference/build-secrets/ and https://fly.io/docs/reference/secrets/

The topic of secrets and the docs will have their own issue to get updated soon too.
