### ISSUE TITLE
how to create a machine using the website

### ISSUE THREAD

**Issue by 1268** [superfly/docs#663]
I just started with Fly, and I am on this page:

https://fly.io/dashboard/personal/machines

and I dont see any way to create a machine. All I see is this:

> No machines
>
> Get started by creating a new machine.
>
> [Go to docs](https://fly.io/docs/machines/working-with-machines)

which leads to a page called "Working with the Machines API". I dont want to work with the API, I just want to click some buttons on the website and have it spit out a machine. Is that possible?

**Comment by catflydotio** [comment]
No, it's not yet possible to launch an app or run a Machine by clicking some buttons. You'd have to use the CLI. 

The good news is that you don't need the API to get a Machine. You can just launch an app instead. Here's a better doc to start with: https://fly.io/docs/hands-on/.

Also have a look at the https://fly.io/dashboard/personal/launch page. There's even a way to use the CLI without leaving the browser...

**Comment by 4cq2** [comment]
I dont want to use "fly app" or whatever you call it, because I dont want to be restricted to a certain set of languages. I want to be free to run programs written in any language. so I think for me a "fly machine" is a better option.

**Comment by catflydotio** [comment]
You can run anything you want in a Fly App. We have launchers to automatically configure and build some kinds of projects, but whether it's an app configured with the help of `fly launch` or a Machine VM, you can run anything you can stuff into a Docker image.

**Comment by 4cq2** [comment]
thanks for the information, but I dont have any experience with Docker. I am used to just running a server on my local computer, and I also have experience running a program on a virtual private server. So it seems like just having the option to launch a virtual machine would be a good fit for me. Currently I am doing this with a Digital Ocean Droplet which is working well, but I always like to check if better options are available.

It seems with Fly that I would either need to learn the Fly Machines API, or learn Docker or both.

**Comment by catflydotio** [comment]
I appreciate your bringing up this issue! It helps us understand how our docs and dashboard can be improved for newcomers.

If you're still curious, I'd suggest bringing your use case to the [community forum](https://community.fly.io/); there's probably not that much Docker involved in getting your droplet equivalent running as a VM on Fly.io, and there are a lot of helpful folks around who've probably done the same thing before.

**Comment by 1268** [comment]
FYI I am still a happy and paying customer of a Digital Ocean Droplet to this day. I am happy to instead give my money to Fly, but the issue I raised here would need to be addressed, and it seems as of today the situation is exactly as it was when I posted the issue.
