### ISSUE TITLE
Link to LiteFS example app walkthrough 404s

### ISSUE THREAD

**Issue by lucas-homer** [superfly/docs#686]
The LiteFS Overview page lists three guides and links to them. The second of three links, the example app walkthrough, links to a page that's missing. The `index.html.md.erb` file links to `/docs/litefs/example` but that file doesn't exist. This results in a 404 response.

**Comment by benbjohnson** [comment]
Thanks, @lucas-homer. I consolidated the _Getting Started_ guide and the example application as there were a lot of similarities. I forgot the redirect though. I added that in https://github.com/superfly/docs/pull/687 so [/docs/litefs/example](https://fly.io/docs/litefs/example) now redirects correctly.
