### ISSUE TITLE
Expand the multiple process docs to include process groups

### ISSUE THREAD

**Issue by jsierles** [superfly/docs#69]
We already have this fun doc: https://fly.io/docs/app-guides/multiple-processes. It throws out a number of options for running multiple process _inside a VM_.

We also have [a feature for running multiple processes as separate VMs in a single app](https://community.fly.io/t/preview-multi-process-apps-get-your-workers-here/2316), aka _process groups_ or _multi-process apps_.

We can augment this section to include something about multiple processes. https://fly.io/docs/app-guides/multiple-processes/#maybe-you-want-multiple-apps-though

**Comment by catflydotio** [comment]
(tie this https://fly.io/docs/reference/configuration/#the-processes-section into this https://fly.io/docs/app-guides/multiple-processes/#maybe-you-want-multiple-apps-though)

**Comment by catflydotio** [comment]
"that page is super old and I hate it" -- Kurt

**Comment by catflydotio** [comment]
On the theme of multi-process apps, we have:

* This doc https://fly.io/docs/app-guides/multiple-processes/, about stuffing various processes (here, different programs) into one VM with an entrypoint script or process manager.
* [processes] in a Nomad app, which is separate VMs with the same image but different entrypoints, all within one app and somehow we send the right request to the right one — still a preview feature, can easily get itself tied up in knots esp regarding regions
* Different images on different Machines VMs under one app. Super early and the proxy and internal DNS are not set up to deal with this situation at all yet, I think (have to use 6pn address directly to an instance). I'm guessing we want to support this in Apps V2 but I'm not sure it's a foregone conclusion.
* Multi-process machines ("sidecar" processes) —a single VM, multiple processes running "from" the same image but with different entrypoints/cmds and environment variables?

**Comment by catflydotio** [comment]
Process groups added in https://github.com/superfly/docs/commit/aee1a0f3e526f3bc6d0267cbd255ee6045f88353
