### ISSUE TITLE
Wrong command for generating Fly API token

### ISSUE THREAD

**Issue by mubaraqwahab** [superfly/docs#713]
Hello 👋🏾

I was following the instructions on the [Continuous Deployment with Fly.io and GitHub Actions](https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/#api-tokens-and-deployment) page in your docs, but when I got to this step:

https://github.com/superfly/docs/blob/13702ce3d3ba92d79152b84a38d7afe6bde60faa/app-guides/continuous-deployment-with-github-actions.html.md?plain=1#L25

The command failed with the following error:

```
Error: unknown command "tokens" for "flyctl"
Run 'flyctl --help' for usage.
Error unknown command "tokens" for "flyctl"
```

However, I found another command in a later part of the article, where you go into detail about the steps:

https://github.com/superfly/docs/blob/13702ce3d3ba92d79152b84a38d7afe6bde60faa/app-guides/continuous-deployment-with-github-actions.html.md?plain=1#L63

And this command worked for me 😃

Is the previous command a mistake? (If it is, and you don't mind, I can create a pull request to fix)

My `flyctl` version is:

```
fly.exe v0.0.470 windows/amd64 Commit: 5b41efb9 BuildDate: 2023-02-25T16:10:28Z
```

**Comment by fideloper** [comment]
Hi there!

I'm not exactly sure when `tokens` was introduced, but I have it here available in my version of Fly (v0.0.544).

It's relatively recent, related to our use of [macaroons](https://community.fly.io/t/deploy-tokens/11895) 

It's important to keep `flyctl` up to date as it contains a lot of functionality (it's not just a thin wrapper around API calls to our admin, but instead does a bunch of orchestration for things like deployments itself).

**Comment by fideloper** [comment]
We'll update these docs a bit as there might be some confusing parts there about which token command to use. Thanks!

**Comment by mubaraqwahab** [comment]
Okay I see. Thank you!
