### ISSUE TITLE
Docs site has layout issue; left nav occludes main reading area

### ISSUE THREAD

**Issue by cweekly** [superfly/docs#88]
macOS Monterey, Firefox seems fine, but check this screenshot from Chrome (v99):

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/67498/157503249-671ec1a3-fff0-45c1-bc56-2b580973774e.png">

**Comment by catflydotio** [comment]
I've seen this before, but not recently. Try a hard refresh?

**Comment by cweekly** [comment]
I've only ever seen it this way in Chrome. No luck w/ refreshing.
