### ISSUE TITLE
broken link: /docs/udp-and-tcp/

### ISSUE THREAD

**Issue by afomi** [superfly/docs#90]
the link, "Run UDP Services", to the path /docs/udp-and-tcp/, is broken

![Screen Shot 2022-03-09 at 10 56 24 PM](https://user-images.githubusercontent.com/67984/157606184-46b4deef-7bae-427e-a265-1f382dd10f02.png)

**Comment by jsierles** [comment]
Thanks! This was fixed in 35e393d5280145310edf016dc0f09501b0c11845.
