### ISSUE TITLE
Undocumented environment variables

### ISSUE THREAD

**Issue by butaca** [superfly/docs#957]
I found the following environment variables which are missing in https://fly.io/docs/reference/runtime-environment/

FLY_IMAGE_REF
FLY_MACHINE_ID
FLY_MACHINE_VERSION
FLY_PRIVATE_IP
FLY_PROCESS_GROUP
FLY_VM_MEMORY_MB

Since they aren't documented, I don't know exactly if they are safe to use.

**Comment by catflydotio** [comment]
Completed with #1059

**Comment by Lucais11** [comment]
#1059

**Comment by butaca** [comment]
Thank you! :)
