### ISSUE TITLE
Nginx config and LiteFS Cloud Dashboards links not working

### ISSUE THREAD

**Issue by yquansah** [superfly/docs#958]
On the getting [Getting Started with LiteFS in Docker](https://fly.io/docs/litefs/getting-started-docker/), the links for nginx config at the bottom and LiteFS Cloud Dashboard do not seem to be working.

This is what I see on my end.
<img width="747" alt="Screenshot 2023-09-02 at 4 50 48 PM" src="https://github.com/superfly/docs/assets/13950726/d1f6b99d-b5f9-44c7-903a-2a22fc55fbf9">

The `[]` brackets around `nginx-config` and `LiteFS Cloud Dashboard` instead of the actual links to those pages.

**Comment by redjonzaci** [comment]
Thanks for the issue!
Taking a look in a few hours.

**Comment by redjonzaci** [comment]
I need some more time with this as I learn how to build the repo and test this.
Maybe a Fly.io employee will look at this soon.

**Comment by redjonzaci** [comment]
I tried, but it seems like only Fly.io employees are allowed to contribute here for now.

**Comment by benbjohnson** [comment]
hey Yoofi! Thanks for reporting the issue. We swapped out our rendering library recently and it doesn't like reference-style Markdown links. I pushed up the fixes and it should be live now. 🎉

**Comment by yquansah** [comment]
@benbjohnson Hey Ben! Thanks for the fix 🙏  hope you are well
