### ISSUE TITLE
Try an example leads to Well this is embarrassing 404 error

### ISSUE THREAD

**Issue by adelton** [superfly/docs#975]
On my dashboard at https://fly.io/dashboard/personal, the last purplish rectangle "Try an example" links to https://fly.io/docs/getting-started/node/. However, that page says

> Error 404
> Well this is embarrassing…
> 
> The page you’re looking for isn’t here. Feel free to return to the [home page](https://fly.io/) or browse the [docs](https://fly.io/docs/) to find what you need.

I'm looking at https://github.com/superfly/docs/tree/main/getting-started and I'm not sure what I need but in general, links should not be broken.

**Comment by redjonzaci** [comment]
I think it needs to be updated to https://fly.io/docs/js/.

**Comment by andie787** [comment]
@adelton Thanks for pointing this out. The 404 part is fixed at least now!
